name: Deploy Staging - All Orchestration Service

on:
  push:
    branches:
      - lais-v2.2

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: orchestration-staging
    steps:
      - name: Deploy to Staging Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/all-staging-user/all-services/all-orchestration-deploy
            ./deploy.sh
